spring:
  application:
    name: front-bff
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: frontbff
              uri: http://localhost:3000
              predicates:
                - Path=/**
              filters:
                - TokenRelay=
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
      client:
        provider:
          itp-frontbff:
            issuer-uri: http://localhost:9090
        registration:
          itp-frontbff:
            provider: itp-frontbff
            client-id: itp-frontbff
            client-secret: qwerqwer
            # redirect to gateway server
            redirect-uri: http://localhost:9990/login/oauth2/code/itp-standard
            authorization-grant-type:
              - authorization_code
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email
server:
  port: 9990

# Enable log Gateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: TRACE
eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true